feat: add support for custom domain proxy
mparticle-integrations/mparticle-apple-integration-urbanairship pull request #28
Opened 2023-12-13 04:44 UTC by ngarg-mparticle

## Summary
 - Read the connection setting "customDomainProxyUrl" and set it 

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - Tested without setting customDomainProxyUrl in mP UI first. The integration worked normally and events were forwarded to Airship.
 - After setting a dummy value "https://analytics.example.com" for customDomainProxyUrl in mP UI, the integration stopped working and I started getting "A server with the specified hostname could not be found." in the Xcode console.
 - Further testing needs to be done with a working custom domain proxy.

2023-12-13 14:48 UTC, einsteinx2 requested changes

2023-12-13 14:48 UTC, einsteinx2 commented on mParticle-UrbanAirship/MPKitUrbanAirship.m
> +        if( self.configuration[UAConfigCustomDomainProxyUrl] ){
```suggestion
        if (self.configuration[UAConfigCustomDomainProxyUrl]) {
```
minor nitpick on spacing to match style of rest of file

2024-02-02 15:08 UTC, BrandonStalnaker commented
@ngarg-mparticle any update on testing this?

2024-03-01 17:18 UTC, ShaneQi commented on mParticle-UrbanAirship/MPKitUrbanAirship.m
> +            config.URLAllowList = @[self.configuration[UAConfigCustomDomainProxyUrl]];
Why are we setting `URLAllowList` to `UAConfigCustomDomainProxyUrl`? I assume this would overwrite the `URLAllowList` populated from the default config, which is probably not what we want to do.

Context: I'm from the customer that requested this feature and I will be testing this.

2024-03-26 16:11 UTC, ngarg-mparticle commented on mParticle-UrbanAirship/MPKitUrbanAirship.m
> +            config.URLAllowList = @[self.configuration[UAConfigCustomDomainProxyUrl]];
@ShaneQi perhaps a better approach would be to append if URLAllowList already exists?

2024-03-29 20:30 UTC, ShaneQi commented on mParticle-UrbanAirship/MPKitUrbanAirship.m
> +        }
@ngarg-mparticle 
we couldn't wait for yall's change due to planning and made the below change for testing.

The below change was tested and verified to be working fine. Please help publish the below change to cocoapods (and other registries if applicable).

```suggestion

        // Enable custom domain proxy if provided
        if (self.configuration[UAConfigCustomDomainProxyUrl]) {
            config.initialConfigURL = self.configuration[UAConfigCustomDomainProxyUrl];
            config.URLAllowList = [config.URLAllowList arrayByAddingObject:self.configuration[UAConfigCustomDomainProxyUrl]];
        }
```

2024-04-03 17:11 UTC, BrandonStalnaker approved these changes
LGTM

2024-04-03 17:11 UTC, merged